---
title: Bevestig weerstanden en jumperkabels aan een RGB-led met isolatietape
hero_image: images/banner.png
description: Bevestig weerstanden en jumperkabels aan een RGB-led met isolatietape
version: 4
listed: false
copyedit: false
last_tested: "2022-01-26"
steps:
  - title: Bevestig weerstanden en jumperdraden aan een RGB-led met isolatietape
