title: Attach resistors and jumper wires to an RGB LED with electrical tape
hero_image: images/banner.png
description: Attach resistors and jumper wires to an RGB LED with electrical tape
version: 4
listed: false
copyedit: false
last_tested: "2022-01-26"
steps:
  - title: Attach resistors and jumper wires to an RGB LED with electrical tape
