title: Attach resistors and jumper wires to an RGB LED with electrical tape
hero_image: images/banner.png
description: rgb-led-resistor-electrical-tape description
version: 4
listed: false
copyedit: false
last_tested: "2022-01-26"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
