---
title: توصيل المقاومات وأسلاك التوصيل بمصباح RGB LED بشريط كهربائي
hero_image: images/banner.png
description: توصيل المقاومات وأسلاك التوصيل بمصباح RGB LED بشريط كهربائي
version: 4
listed: false
copyedit: false
last_tested: "2022-01-26"
steps:
  - title: توصيل المقاومات وأسلاك التوصيل بمصباح RGB LED بشريط كهربائي
