---
title: Fixer les résistances et les câbles de connexion à une LED RVB avec du ruban électrique
hero_image: images/banner.png
description: Fixer les résistances et les câbles de connexion à une LED RVB avec du ruban électrique
version: 4
listed: false
copyedit: false
last_tested: "2022-01-26"
steps:
  - title: Fixer les résistances et les câbles de connexion à une LED RVB avec du ruban électrique
